# Generated by Django 4.2.28 on 2026-02-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, help_text='RFC del cliente (12 o 13 caracteres)', max_length=13, unique=True)),
                ('razon_social', models.CharField(help_text='Razón social del cliente', max_length=255)),
                ('email', models.EmailField(help_text='Correo electrónico del cliente', max_length=255)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa (calle, número, colonia)')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal', max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
